version: '2'
services:

  zabbix-db:
    image: mariadb:10.1
    container_name: zabbix-db
    volumes:
      - /var/container_data/zabbix/db_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix
      - MYSQL_ROOT_PASSWORD=1amr00t!

  zabbix-java-gateway:
    container_name: zabbix-java-gateway
    image: zabbix/zabbix-java-gateway:latest
    ports:
      - "10052:10052"
    #volumes:
    #  - /var/container_data/zabbix/zabbix_java_gateway.conf:/etc/zabbix/zabbix_java_gateway.conf:rw

  zabbix-server:
    container_name: zabbix-server
    image: zabbix/zabbix-server-mysql:latest
    environment: 
      - DB_SERVER_HOST=zabbix-db
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix
      - MYSQL_ROOT_PASSWORD=1amr00t!
      - ZBX_JAVAGATEWAY=zabbix-java-gateway
      - ZBX_ENABLE_SNMP_TRAPS=true
    links: 
      - zabbix-db:zabbix-db
      - zabbix-java-gateway:zabbix-java-gateway
    ports:
      - "10051:10051"
    volumes:
      - /var/container_data/zabbix/alertscripts:/usr/lib/zabbix/alertscripts:rw
    volumes_from:
      - zabbix-snmptraps:rw
  
  zabbix-web:
    container_name: zabbix-web
    image: zabbix/zabbix-web-nginx-mysql:latest
    environment:
      - DB_SERVER_HOST=zabbix-db
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix
      - MYSQL_ROOT_PASSWORD=1amr00t!
    links:
      - zabbix-db:zabbix-db
      - zabbix-server:zabbix-server
    ports:
      - "8088:80"

  zabbix-snmptraps:
    container_name: zabbix-snmptraps
    image: zabbix/zabbix-snmptraps:latest
    volumes:
      - /var/container_data/zabbix/snmptraps:/var/lib/zabbix/snmptraps:rw
      - /var/container_data/zabbix/mibs:/usr/share/snmp/mibs:rw
    ports:
      - "162:162/udp"
