# Configuration of the embedded HTTP server.
http:
  listen:
    # Basic HTTP.
    -
      host: '0.0.0.0'
      port: 4443
      certificate : '/ssl/lu.smctr.net.crt'
      key : '/ssl/lu.smctr.net.key'

  mounts:
    '/': '/home/node/xen-orchestra/packages/xo-web/dist/'

# Connection to the Redis server.
redis:
    uri: "redis://redis:6379"

datadir: '/storage/data'

