version: '3'
services:

  squid:
    image: sameersbn/squid:3.5.27-2
    container_name: squid
    ports:
      - "3128:3128"
    volumes:
      - /opt/container_data/squid/spool:/var/spool/squid
      - /opt/container_data/squid/log:/var/log/squid
      - /opt/container_data/squid/squid.conf:/etc/squid/squid.conf
    restart: always
