version: "3"
services:
  squid:
    image: alpine-docker-squid:5.7
    container_name: docker-squid
    network_mode: "host"
    #environment:
    ports:
      - "3128:3128"
    volumes:
      - /var/cache/squid:/var/cache/squid:rw
      - /var/container_data/squid/squid.conf:/etc/squid/squid.conf
      - /var/log/squid:/var/log/squid:rw
    restart: always
